---
title: "Jessica Villa"
author: "Your Name"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I went to East Side High School and I graduated in 2013. I feel like English is a little harder for me because of the essays and I feel like math is more simple because you just solve problems and depending what math class it is you have to follow formulas, eguations, etc. I think my best subject was math. 
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
Apple. I would rate myself a 7. My internet connection is good.   
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
 I don't have a preference. My full first name Jessica would be fine. 
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
My goal is to become a registered nurse and once I have enough experience I would like to become a travel nurse. I think the subject that would interest me the most would be anatomy. My goal is to achieve an associates degree in registered nursing and then later on get my BSN.   
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
 I've gone to Mexico before my mom's home town. Which is located in Torreon, Coahuila but that was when I was 9 years old. In 2019 I went to Hawaii I visited the big island which is Kona but where I've been wanting to go for a long time already is Thailand. No I have not been in the military. 
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  I took math 115 a couple of years ago but never finished the class so this is my second time taking Math 115. Yes, I knew Math 114 is a general requirement but I never knew that Math 116 counts for transfer. I need to achieve an A in Math 115 because for the RN program my grade for Math 115 and English 101 gets combined together to get a gpa and with that gpa it gives me points and those points will give me a greater advantage to get into the RN program sooner. My plan is to work hard to get an A in Math 115 :)
   
 






  




